const secondsInAMinute = 60; 
const minutesInAnOur = 60;
const secondsInAnOur = secondsInAMinute * minutesInAnOur;
const hoursInADay = 24;
const secondsInADay = secondsInAnOur * hoursInADay;
const daysInAnYear = 365;
const secondsInAnYear = daysInAnYear * secondsInADay;
const myAge = 24;
const myAgeInASeconds = secondsInAnYear * myAge;
console.log(myAgeInASeconds);